package com.example.demo.model;

import java.time.LocalDate;

public class Introduction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.introduction_id
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private Integer introductionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.user_id
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.name
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.kana
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private String kana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.gender
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.hobby
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.word
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.created_at
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private LocalDate createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column introductions.updated_at
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    private LocalDate updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.introduction_id
     *
     * @return the value of introductions.introduction_id
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public Integer getIntroductionId() {
        return introductionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.introduction_id
     *
     * @param introductionId the value for introductions.introduction_id
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setIntroductionId(Integer introductionId) {
        this.introductionId = introductionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.user_id
     *
     * @return the value of introductions.user_id
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.user_id
     *
     * @param userId the value for introductions.user_id
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.name
     *
     * @return the value of introductions.name
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.name
     *
     * @param name the value for introductions.name
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.kana
     *
     * @return the value of introductions.kana
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public String getKana() {
        return kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.kana
     *
     * @param kana the value for introductions.kana
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setKana(String kana) {
        this.kana = kana == null ? null : kana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.gender
     *
     * @return the value of introductions.gender
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.gender
     *
     * @param gender the value for introductions.gender
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.hobby
     *
     * @return the value of introductions.hobby
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.hobby
     *
     * @param hobby the value for introductions.hobby
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.word
     *
     * @return the value of introductions.word
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.word
     *
     * @param word the value for introductions.word
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.created_at
     *
     * @return the value of introductions.created_at
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public LocalDate getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.created_at
     *
     * @param createdDate the value for introductions.created_at
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setCreatedDate(LocalDate createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column introductions.updated_at
     *
     * @return the value of introductions.updated_at
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public LocalDate getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column introductions.updated_at
     *
     * @param updatedDate the value for introductions.updated_at
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    public void setUpdatedDate(LocalDate updatedDate) {
        this.updatedDate = updatedDate;
    }
}