package com.example.demo.model;

import java.util.Date;

import com.example.demo.form.SignupForm;

import lombok.Data;

@Data
public class User {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.user_id
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.email
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.created_at
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	private Date createdDate;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.user_id
	 * @return  the value of users.user_id
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	public String getUserId() {
		return userId;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.user_id
	 * @param userId  the value for users.user_id
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.email
	 * @return  the value of users.email
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	public String getEmail() {
		return email;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.email
	 * @param email  the value for users.email
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	public String getPassword() {
		return password;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.created_at
	 * @return  the value of users.created_at
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	public Date getCreatedDate() {
		return createdDate;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.created_at
	 * @param createdDate  the value for users.created_at
	 * @mbg.generated  Sun Nov 05 17:22:24 JST 2023
	 */
	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	public void importForm(SignupForm form) {
		this.userId = form.getUserId();
		this.email = form.getEmail();
		this.password = form.getPassword();
	}
}
