package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.model.Introduction;
import com.example.demo.model.IntroductionExample;

@Mapper
public interface IntroductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    long countByExample(IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    int deleteByExample(IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    int deleteByPrimaryKey(Integer introductionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    int insert(Introduction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    int insertSelective(Introduction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    List<Introduction> selectByExample(IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    Introduction selectByPrimaryKey(Integer introductionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    int updateByExampleSelective(@Param("row") Introduction row, @Param("example") IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    int updateByExample(@Param("row") Introduction row, @Param("example") IntroductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    int updateByPrimaryKeySelective(Introduction row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table introductions
     *
     * @mbg.generated Sat Nov 18 21:59:14 JST 2023
     */
    int updateByPrimaryKey(Introduction row);
    
    Introduction selectByUserId(String userId);
}