package com.example.demo.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.mybatis.dmain.Introductions;
import com.example.demo.mybatis.dmain.IntroductionsExample;

@Mapper
public interface IntroductionsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	long countByExample(IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	int deleteByExample(IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	int insert(Introductions row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	int insertSelective(Introductions row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	List<Introductions> selectByExample(IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	Introductions selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	int updateByExampleSelective(@Param("row") Introductions row, @Param("example") IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	int updateByExample(@Param("row") Introductions row, @Param("example") IntroductionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	int updateByPrimaryKeySelective(Introductions row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.introductions
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	int updateByPrimaryKey(Introductions row);
}