package com.example.demo.mybatis.dmain;

import java.util.Date;

public class Introductions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.introduction
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private Integer introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.user_id
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.name
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.kana
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String kana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.gender
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.hobby
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String hobby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.word
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.create_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private Date create_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.introductions.updated_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private Date updated_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.introduction
     *
     * @return the value of public.introductions.introduction
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public Integer getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.introduction
     *
     * @param introduction the value for public.introductions.introduction
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setIntroduction(Integer introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.user_id
     *
     * @return the value of public.introductions.user_id
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.user_id
     *
     * @param user_id the value for public.introductions.user_id
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.name
     *
     * @return the value of public.introductions.name
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.name
     *
     * @param name the value for public.introductions.name
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.kana
     *
     * @return the value of public.introductions.kana
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getKana() {
        return kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.kana
     *
     * @param kana the value for public.introductions.kana
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setKana(String kana) {
        this.kana = kana == null ? null : kana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.gender
     *
     * @return the value of public.introductions.gender
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.gender
     *
     * @param gender the value for public.introductions.gender
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.hobby
     *
     * @return the value of public.introductions.hobby
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.hobby
     *
     * @param hobby the value for public.introductions.hobby
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.word
     *
     * @return the value of public.introductions.word
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.word
     *
     * @param word the value for public.introductions.word
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.create_at
     *
     * @return the value of public.introductions.create_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public Date getCreate_at() {
        return create_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.create_at
     *
     * @param create_at the value for public.introductions.create_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setCreate_at(Date create_at) {
        this.create_at = create_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.introductions.updated_at
     *
     * @return the value of public.introductions.updated_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.introductions.updated_at
     *
     * @param updated_at the value for public.introductions.updated_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }
}