package com.example.demo.mybatis.dmain;

public class Introductions {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.id
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.name
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.kana
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	private String kana;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.gender
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.hobby
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	private String hobby;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.introductions.word
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	private String word;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.introductions.id
	 * @return  the value of public.introductions.id
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.introductions.id
	 * @param id  the value for public.introductions.id
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.introductions.name
	 * @return  the value of public.introductions.name
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.introductions.name
	 * @param name  the value for public.introductions.name
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.introductions.kana
	 * @return  the value of public.introductions.kana
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public String getKana() {
		return kana;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.introductions.kana
	 * @param kana  the value for public.introductions.kana
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public void setKana(String kana) {
		this.kana = kana == null ? null : kana.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.introductions.gender
	 * @return  the value of public.introductions.gender
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.introductions.gender
	 * @param gender  the value for public.introductions.gender
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public void setGender(String gender) {
		this.gender = gender == null ? null : gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.introductions.hobby
	 * @return  the value of public.introductions.hobby
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public String getHobby() {
		return hobby;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.introductions.hobby
	 * @param hobby  the value for public.introductions.hobby
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public void setHobby(String hobby) {
		this.hobby = hobby == null ? null : hobby.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.introductions.word
	 * @return  the value of public.introductions.word
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public String getWord() {
		return word;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.introductions.word
	 * @param word  the value for public.introductions.word
	 * @mbg.generated  Sat Dec 02 01:21:03 GMT+09:00 2023
	 */
	public void setWord(String word) {
		this.word = word == null ? null : word.trim();
	}
}