package com.example.demo.mybatis.dmain;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.user_id
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.email
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.password
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.created_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    private Date created_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.user_id
     *
     * @return the value of public.users.user_id
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.user_id
     *
     * @param user_id the value for public.users.user_id
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.email
     *
     * @return the value of public.users.email
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.email
     *
     * @param email the value for public.users.email
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.password
     *
     * @return the value of public.users.password
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.password
     *
     * @param password the value for public.users.password
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.users.created_at
     *
     * @return the value of public.users.created_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public Date getCreated_at() {
        return created_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.users.created_at
     *
     * @param created_at the value for public.users.created_at
     *
     * @mbg.generated Mon Oct 30 10:48:53 GMT+09:00 2023
     */
    public void setCreated_at(Date created_at) {
        this.created_at = created_at;
    }
}